version: "2"  # 配置文件版本：2

run:  # 运行配置
  tests: false  # 是否运行测试：否

linters:  # 代码检查器配置
  enable:  # 启用的检查器
    - bodyclose  # 检查 io.Reader 的 body 是否关闭
    - exhaustive  # 检查 switch 语句是否穷尽所有枚举值
    - goconst  # 查找重复的字符串常量
    - godot  # 检查注释是否以句点结尾
    - godox  # 检查注释中是否包含 TODO、FIXME 等标记
    - gomoddirectives  # 检查 go.mod 指令的使用
    - goprintffuncname  # 检查 fmt.Printf 风格函数的命名
    - gosec  # 检查常见的安全问题
    - misspell  # 检查拼写错误
    - nakedret  # 检查裸返回语句
    - nestif  # 检查嵌套过深的 if 语句
    - nilerr  # 检查忽略 nil 错误
    - noctx  # 检查是否有 context.Background() 或 TODO
    - nolintlint  # 检查 nolint 注释是否有效
    - prealloc  # 建议预先分配切片容量
    - revive  # Go 代码检查器（更严格的代码规范）
    - rowserrcheck  # 检查 sql.Rows 是否正确关闭
    - sqlclosecheck  # 检查 sql.Rows 和 sql.Stmt 是否关闭
    - tparallel  # 检查 T.Parallel() 的使用
    - unconvert  # 检查不必要的类型转换
    - unparam  # 检查未使用的函数参数
    - whitespace  # 检查代码中的空白问题
    - wrapcheck  # 检查错误包装是否包含足够信息
  exclusions:  # 排除规则
    generated: lax  # 生成代码：宽松模式
    presets:  # 预设配置
      - common-false-positives  # 常见误报：启用

issues:  # 问题报告配置
  max-issues-per-linter: 0  # 每个检查器最大问题数：0（无限制）
  max-same-issues: 0  # 相同问题最大出现次数：0（无限制）

formatters:  # 代码格式化器配置
  enable:  # 启用的格式化器
    - gofumpt  # Go 代码格式化工具（更严格的格式）
    - goimports  # Go 导入排序格式化工具
  exclusions:  # 排除规则
    generated: lax  # 生成代码：宽松模式
